version: '3.3'

services:
  nginx:
    container_name: ${CONTAINER_NAME}-nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      HOSTNAME: ${HOSTNAME}
    ports:
      - "80:80"
      - "443:443"
      
volumes:
  dbdata:
  wordpress:

networks:
  my_network:
    driver: bridge
